/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_hf_leveldb_implementation_NativeIterator */

#ifndef _Included_com_github_hf_leveldb_implementation_NativeIterator
#define _Included_com_github_hf_leveldb_implementation_NativeIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_hf_leveldb_implementation_NativeIterator
 * Method:    nclose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_implementation_NativeIterator_nativeClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeIterator
 * Method:    nvalid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_hf_leveldb_implementation_NativeIterator_nativeValid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeIterator
 * Method:    nseek
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_implementation_NativeIterator_nativeSeek
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeIterator
 * Method:    nseekToFirst
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_implementation_NativeIterator_nativeSeekToFirst
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeIterator
 * Method:    nseekToLast
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_implementation_NativeIterator_nativeSeekToLast
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeIterator
 * Method:    nnext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_implementation_NativeIterator_nativeNext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeIterator
 * Method:    nprev
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_implementation_NativeIterator_nativePrev
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeIterator
 * Method:    nkey
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_github_hf_leveldb_implementation_NativeIterator_nativeKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeIterator
 * Method:    nvalue
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_github_hf_leveldb_implementation_NativeIterator_nativeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
