/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_hf_leveldb_implementation_NativeLevelDB */

#ifndef _Included_com_github_hf_leveldb_implementation_NativeLevelDB
#define _Included_com_github_hf_leveldb_implementation_NativeLevelDB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_hf_leveldb_implementation_NativeLevelDB
 * Method:    nopen
 * Signature: (ZIIILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_github_hf_leveldb_implementation_NativeLevelDB_nativeOpen
  (JNIEnv *, jclass, jboolean, jint, jint, jint, jstring);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeLevelDB
 * Method:    nclose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_implementation_NativeLevelDB_nativeClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeLevelDB
 * Method:    nput
 * Signature: (JZ[B[B)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_implementation_NativeLevelDB_nativePut
  (JNIEnv *, jclass, jlong, jboolean, jbyteArray, jbyteArray);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeLevelDB
 * Method:    ndelete
 * Signature: (JZ[B)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_implementation_NativeLevelDB_nativeDelete
  (JNIEnv *, jclass, jlong, jboolean, jbyteArray);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeLevelDB
 * Method:    nwrite
 * Signature: (JZJ)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_implementation_NativeLevelDB_nativeWrite
  (JNIEnv *, jclass, jlong, jboolean, jlong);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeLevelDB
 * Method:    nget
 * Signature: (J[BJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_github_hf_leveldb_implementation_NativeLevelDB_nativeGet
  (JNIEnv *, jclass, jlong, jbyteArray, jlong);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeLevelDB
 * Method:    ngetProperty
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_github_hf_leveldb_implementation_NativeLevelDB_nativeGetProperty
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeLevelDB
 * Method:    ndestroy
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_implementation_NativeLevelDB_nativeDestroy
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeLevelDB
 * Method:    nrepair
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_implementation_NativeLevelDB_nativeRepair
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeLevelDB
 * Method:    niterate
 * Signature: (JZJ)J
 */
JNIEXPORT jlong JNICALL Java_com_github_hf_leveldb_implementation_NativeLevelDB_nativeIterate
  (JNIEnv *, jclass, jlong, jboolean, jlong);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeLevelDB
 * Method:    nsnapshot
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_github_hf_leveldb_implementation_NativeLevelDB_nativeSnapshot
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeLevelDB
 * Method:    nreleaseSnapshot
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_implementation_NativeLevelDB_nativeReleaseSnapshot
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
