/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_hf_leveldb_LevelDB */

#ifndef _Included_com_github_hf_leveldb_LevelDB
#define _Included_com_github_hf_leveldb_LevelDB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_hf_leveldb_LevelDB
 * Method:    nopen
 * Signature: (ZIIILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_github_hf_leveldb_LevelDB_nopen
  (JNIEnv *, jclass, jboolean, jint, jint, jint, jstring);

/*
 * Class:     com_github_hf_leveldb_LevelDB
 * Method:    nclose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_LevelDB_nclose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_hf_leveldb_LevelDB
 * Method:    nput
 * Signature: (JZ[B[B)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_LevelDB_nput
  (JNIEnv *, jclass, jlong, jboolean, jbyteArray, jbyteArray);

/*
 * Class:     com_github_hf_leveldb_LevelDB
 * Method:    ndelete
 * Signature: (JZ[B)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_LevelDB_ndelete
  (JNIEnv *, jclass, jlong, jboolean, jbyteArray);

/*
 * Class:     com_github_hf_leveldb_LevelDB
 * Method:    nwrite
 * Signature: (JZJ)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_LevelDB_nwrite
  (JNIEnv *, jclass, jlong, jboolean, jlong);

/*
 * Class:     com_github_hf_leveldb_LevelDB
 * Method:    nget
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_github_hf_leveldb_LevelDB_nget
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_github_hf_leveldb_LevelDB
 * Method:    ngetProperty
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_github_hf_leveldb_LevelDB_ngetProperty
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_github_hf_leveldb_LevelDB
 * Method:    ndestroy
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_LevelDB_ndestroy
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_github_hf_leveldb_LevelDB
 * Method:    nrepair
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_LevelDB_nrepair
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
