/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_hf_leveldb_implementation_NativeLevelDB */

#ifndef _Included_com_github_hf_leveldb_implementation_NativeLevelDB
#define _Included_com_github_hf_leveldb_implementation_NativeLevelDB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_hf_leveldb_implementation_NativeLevelDB
 * Method:    nopen
 * Signature: (ZZZZIIIILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_github_hf_leveldb_implementation_NativeLevelDB_nopen
  (JNIEnv *, jclass, jboolean, jboolean, jboolean, jboolean, jint, jint, jint, jint, jstring);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeLevelDB
 * Method:    nclose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_implementation_NativeLevelDB_nclose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeLevelDB
 * Method:    nput
 * Signature: (JZ[B[B)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_implementation_NativeLevelDB_nput
  (JNIEnv *, jclass, jlong, jboolean, jbyteArray, jbyteArray);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeLevelDB
 * Method:    ndelete
 * Signature: (JZ[B)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_implementation_NativeLevelDB_ndelete
  (JNIEnv *, jclass, jlong, jboolean, jbyteArray);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeLevelDB
 * Method:    nwrite
 * Signature: (JZJ)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_implementation_NativeLevelDB_nwrite
  (JNIEnv *, jclass, jlong, jboolean, jlong);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeLevelDB
 * Method:    nget
 * Signature: (J[BJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_github_hf_leveldb_implementation_NativeLevelDB_nget
  (JNIEnv *, jclass, jlong, jbyteArray, jlong);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeLevelDB
 * Method:    ngetProperty
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_github_hf_leveldb_implementation_NativeLevelDB_ngetProperty
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeLevelDB
 * Method:    ndestroy
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_implementation_NativeLevelDB_ndestroy
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeLevelDB
 * Method:    nrepair
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_implementation_NativeLevelDB_nrepair
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeLevelDB
 * Method:    niterate
 * Signature: (JZJ)J
 */
JNIEXPORT jlong JNICALL Java_com_github_hf_leveldb_implementation_NativeLevelDB_niterate
  (JNIEnv *, jclass, jlong, jboolean, jlong);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeLevelDB
 * Method:    nsnapshot
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_github_hf_leveldb_implementation_NativeLevelDB_nsnapshot
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_hf_leveldb_implementation_NativeLevelDB
 * Method:    nreleaseSnapshot
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_implementation_NativeLevelDB_nreleaseSnapshot
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
