/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_hf_leveldb_Iterator */

#ifndef _Included_com_github_hf_leveldb_Iterator
#define _Included_com_github_hf_leveldb_Iterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_hf_leveldb_Iterator
 * Method:    nclose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_Iterator_nclose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_hf_leveldb_Iterator
 * Method:    nvalid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_hf_leveldb_Iterator_nvalid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_hf_leveldb_Iterator
 * Method:    nseek
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_Iterator_nseek
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_github_hf_leveldb_Iterator
 * Method:    nseekToFirst
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_Iterator_nseekToFirst
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_hf_leveldb_Iterator
 * Method:    nseekToLast
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_Iterator_nseekToLast
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_hf_leveldb_Iterator
 * Method:    nnext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_Iterator_nnext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_hf_leveldb_Iterator
 * Method:    nprev
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_hf_leveldb_Iterator_nprev
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_hf_leveldb_Iterator
 * Method:    nkey
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_github_hf_leveldb_Iterator_nkey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_hf_leveldb_Iterator
 * Method:    nvalue
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_github_hf_leveldb_Iterator_nvalue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
