#!/bin/bash

JNI_PREBUILD_DIR=`dirname $0`
JAVA_SOURCES_DIR=$JNI_PREBUILD_DIR/../java

NATIVE_SOURCES='com.github.hf.leveldb.implementation.NativeLevelDB com.github.hf.leveldb.implementation.NativeWriteBatch com.github.hf.leveldb.implementation.NativeIterator'

javah -d $JNI_PREBUILD_DIR -classpath $JAVA_SOURCES_DIR $NATIVE_SOURCES
