#!/bin/bash

PREBUILD_DIR=`dirname $0`
PREBUILD_CHECKSUM=`find $PREBUILD_DIR -type f -name "*" -exec md5sum {} + | awk '{print $1}' | sort | md5sum`

JNI_DIR=$PREBUILD_DIR/../jni
JNI_LIBS_DIR=$PREBUILD_DIR/../jniLibs

LIBS_DIR=$PREBUILD_DIR/../libs

BUILD_DIR=$PREBUILD_DIR/../../../build
CHECKSUM_FILE=$BUILD_DIR/jni-prebuild-checksum

if [ -f $CHECKSUM_FILE ] && [ -d $JNI_LIBS_DIR ]
  then

  echo $PREBUILD_CHECKSUM | cmp $CHECKSUM_FILE -
  CMP_STATUS=$?

  if [ $CMP_STATUS -eq 0 ]
    then

    echo "Not compiling, sources have not changed."
    exit 0
  fi
fi

rm -f $CHECKSUM_FILE

rm -rf $JNI_DIR
rm -fr $JNI_LIBS_DIR
cp -r $PREBUILD_DIR $JNI_DIR

ndk-build --directory $JNI_DIR

BUILD_STATUS=$?

if [ $BUILD_STATUS -eq 0 ]
  then
  echo $PREBUILD_CHECKSUM > $CHECKSUM_FILE
  cp -r $LIBS_DIR $JNI_LIBS_DIR
fi

rm -rf $JNI_DIR

exit $BUILD_STATUS




